default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: myrailsapp_development
  username: myrailsapp
  password: <%= ENV['MYRAILSAPP_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: myrailsapp_test
  username: myrailsapp
  password: <%= ENV['MYRAILSAPP_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: myrailsapp_production
  # username: myrailsapp
  # password: <%= ENV['MYRAILSAPP_DATABASE_PASSWORD'] %>
